# Generated by Django 5.1.1 on 2024-12-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESP32Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mqtt_status', models.CharField(max_length=50)),
                ('gas', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=10)),
                ('steer', models.CharField(max_length=10)),
                ('distance', models.FloatField()),
            ],
        ),
    ]
