# Generated by Django 5.1.1 on 2024-12-04 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userakun',
        ),
    ]
