# Generated by Django 5.1.1 on 2024-12-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_rename_user_userakun'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ESP32Data',
        ),
    ]
