# Generated by Django 5.1.1 on 2024-12-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_sensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fire_image', models.ImageField(upload_to='fire_images/')),
            ],
        ),
    ]
